version: '2'
services:
  cpsrv:
    build:
      context: .
      dockerfile: docker/dockerfile_cpsrv
    volumes:
      - ./data/banks:/var/lib/cpsrv/data/banks:ro
    depends_on:
      - tarantool
    networks:
      cpnet:
    ports:
      - "8080:80"
  tarantool:
    build:
      context: .
      dockerfile: docker/dockerfile_tnt
    volumes:
      - ./tnt_workdir/init_docker.lua:/var/lib/cpsrv/lua/init.lua:ro
      - ./tnt_workdir/api:/var/lib/cpsrv/lua/api:ro
      - ./tnt_workdir/snap:/var/lib/cpsrv/snap
      - ./tnt_workdir/wal:/var/lib/cpsrv/wal
    command: tarantool /var/lib/cpsrv/lua/init.lua
    networks:
      cpnet:
networks:
  cpnet:
